<?php
if(!defined('IN_GAME')) exit('Access Denied');

$mixinfo = array
	( 
	array('class' => 'h', 'stuff' => array('雜炊','松茸'),'result' => array('松茸御飯','HS',120,2,),'karma1'=>'-233','karma2'=>'1048576',),
	array('class' => 'h', 'stuff' => array('雜炊','松茸'),'result' => array('松茸御飯','HS',120,2,),),
	array('class' => 'h', 'stuff' => array('咖喱','麪包'),'result' => array('咖喱麪包','HH',140,2,),),
	array('class' => 'h', 'stuff' => array('牛奶','立頓茶包','糯米丸子'),'result' => array('珍珠奶茶','HB',200,4,),),
	array('class' => 'h', 'stuff' => array('早苗麪包','像圍棋子一樣的餅乾','濃厚粘稠果汁','桔黃色的果醬'),'result' => array('KEY系兒童套餐','HB',333,9,),),
	array('class' => 'h', 'stuff' => array('針筒','療傷藥',),'result' => array('治療針','HH',200,5,),),
	array('class' => 'h', 'stuff' => array('麪包','礦泉水','鍋？'),'result' => array('☆法式長棍麪包☆','HB',100,2,),),
	array('class' => 'h', 'stuff' => array('治療針','體力回覆藥','蒸餾水'),'result' => array('特級恢復藥','HB',120,2,),),	
	array('class' => 'h', 'stuff' => array('甜生薑','地雷酥糖'),'result' => array('曾經的榮光-橙黃','HB',50,1,),),
	array('class' => 'h', 'stuff' => array('曾經的榮光-橙黃','麪包'),'result' => array('更改菜譜後的不甜醬包','HB',300,3,'Z'),),

	
	array('class' => 'wc', 'stuff' => array('汽油','空瓶'),'result' => array('☆火焰瓶☆','WC',80,50,'ud'),),	
	array('class' => 'wc', 'stuff' => array('幻之使魔','永恆之桶'),'result' => array('靈魂的結晶','WC',180,240,'rn'),),
	array('class' => 'wc', 'stuff' => array('幻符【殺人玩偶】','★時停懷錶★','永恆飛刃'),'result' => array('幻葬『夜霧幻影殺人鬼』','WC',300,'∞','irnN'),),
	
	array('class' => 'wk', 'stuff' => array('針筒','毒藥'),'result' => array('毒針','WK',32,20,'p'),),	
	array('class' => 'wk', 'stuff' => array('毒針','毒針'),'result' => array('D.毒針','WK',48,20,'p'),),
	array('class' => 'wk', 'stuff' => array('D.毒針','D.毒針','D.毒針'),'result' => array('D.D.D','WK',80,20,'pN'),),
	array('class' => 'wk', 'stuff' => array('白色的羽毛','白色的羽毛','白色的羽毛','白色的羽毛','白色的羽毛'),'result' => array('純白片翼','WK',150,200,'ia'),),
	array('class' => 'wk', 'stuff' => array('白色的羽毛','閃耀的羽毛','彩虹光芒的羽毛','翼人的羽毛'),'result' => array('悲嘆片翼','WK',3200,200,'ai'),),
	array('class' => 'wk', 'stuff' => array('白色的羽毛','鳳凰之羽','露琪亞之羽','綠寶石方塊'),'result' => array('精靈片翼','WK',300,200,'uid'),),
	array('class' => 'wk', 'stuff' => array('『祝福寶石』','『風魔激光刃』'),'result' => array('Azurewrath','WK',50,9999,'rci'),),
	array('class' => 'wk', 'stuff' => array('綠色方塊','綠色方塊'),'result' => array('沾滿綠鏽的銅刀','WK',52,52,'p'),),
	array('class' => 'wk', 'stuff' => array('沾滿綠鏽的銅刀','『祝福寶石』'),'result' => array('妖刀【飛葉】','WK',52,52,'Xrp'),),
	array('class' => 'wk', 'stuff' => array('妖刀【飛葉】','★全地圖唯一的野生高傷闊劍地雷★'),'result' => array('影刀【秋嵐】','WK',522,522,'Zrpd'),),
	array('class' => 'wk', 'stuff' => array('冰封的『Oathkeeper』','火把'),'result' => array('『Oathkeeper』','WK',300,10,'u'),),
	array('class' => 'wk', 'stuff' => array('冰封的『Oathkeeper』','解凍藥水'),'result' => array('『Oathkeeper』','WK',300,10,'u'),),
	array('class' => 'wk', 'stuff' => array('冰封的『Oblivion』','火把'),'result' => array('『Oblivion』','WK',300,10,'i'),),
	array('class' => 'wk', 'stuff' => array('冰封的『Oblivion』','解凍藥水'),'result' => array('『Oblivion』','WK',300,10,'i'),),
	array('class' => 'wk', 'stuff' => array('『Oathkeeper』','『Oblivion』'),'result' => array('『Two Become One』','WK',450,20,'ui'),),
	array('class' => 'wk', 'stuff' => array('悲嘆之種','《尋星流奧義書》','D.D.D','『Two Become One』'),'result' => array('『Last Remote』','WK',10000,1000,'ZNrfk'),),
	
	array('class' => 'wp', 'stuff' => array('電擊鞭','原型武器P','實驗裝甲A','某種電子零件'),'result' => array('『T-LINK念動衝拳』','WP',180,50,'e'),),
	array('class' => 'wp', 'stuff' => array('☆電擊器☆','原型武器P','實驗裝甲A','某種電子零件'),'result' => array('『T-LINK念動衝拳』','WP',240,50,'e'),),
	array('class' => 'wp', 'stuff' => array('『T-LINK念動衝拳』','某種機械設備','增幅設備'),'result' => array('『T-LINK天上天下念動連擊拳』','WP',450,50,'erN'),),
	array('class' => 'wp', 'stuff' => array('【北斗百裂拳】','《北斗神拳》'),'result' => array('【北斗有情破顏拳】','WP',390,100,'drn'),),
	array('class' => 'wp', 'stuff' => array('☆金屬拳套☆','壓縮氣罐','★RPG-7★'),'result' => array('☆簡易火箭飛拳☆','WP',160,'100','cd'),),
	array('class' => 'wp', 'stuff' => array('☆簡易火箭飛拳☆','電磁發射裝置'),'result' => array('★火箭飛拳★','WP',600,500,'cdN'),),
	array('class' => 'wp', 'stuff' => array('《哲♂學》','小棍棒','增幅設備'),'result' => array('森之妖精的棍棒','WP',200,60,'re'),),
	
	array('class' => 'wg', 'stuff' => array('火把','紅寶石方塊','某種電子零件'),'result' => array('『紅石電路』','X',1,1,''),),
	array('class' => 'wg', 'stuff' => array('『環形激光』','『紅石電路』','原型武器G'),'result' => array('『紅石光束炮』','WG',280,280,'udo'),),
	array('class' => 'wg', 'stuff' => array('老式火槍','原型武器G','定時炸彈','某種電子零件'),'result' => array('★發條式突擊步槍★','WG',150,100,'r'),),
	array('class' => 'wg', 'stuff' => array('『60mm火神炮』','鯊魚鰭','原型武器G','某種電子零件'),'result' => array('『迷你鯊』','WG',92,120,'rc'),),
	array('class' => 'wg', 'stuff' => array('『120mm火神炮』','鯊魚鰭','原型武器G','某種電子零件'),'result' => array('『迷你鯊』','WG',120,120,'rc'),),
	array('class' => 'wg', 'stuff' => array('『迷你鯊』','非法槍械部件','某種機械設備'),'result' => array('『巨獸鯊』','WG',294,240,'rc'),),
	array('class' => 'wg', 'stuff' => array('『迷你鯊』','非法槍械部件','原型武器D'),'result' => array('『加農鯊』','WG',480,240,'dco'),),
	array('class' => 'wg', 'stuff' => array('噴霧器罐','打火機','汽油'),'result' => array('★簡易火焰放射器★','WG',150,80,'uo'),),
	array('class' => 'wg', 'stuff' => array('★闊劍地雷★','非法槍械部件','電磁發射裝置'),'result' => array('【定向闊劍發射器】','WG',800,16,'dNo'),),
	array('class' => 'wg', 'stuff' => array('★M-200狙擊步槍★','非法槍械部件','電磁發射裝置'),'result' => array('【磁軌狙擊步槍】','WG',640,240,'edno'),),
	array('class' => 'wg', 'stuff' => array('『高性能環形激光』','『高性能黑洞激光』','『高性能雙重激光』'),'result' => array('☆金色閃光☆','WJ',700,1,'NS'),),
	array('class' => 'wg', 'stuff' => array('恐龍玩偶','天使玩偶','糰子玩偶'),'result' => array('觀鈴的嘎哦嘎哦恐龍噴火分隊','WG',333,10,'ufr'),),
	array('class' => 'wg', 'stuff' => array('水瀨 名雪的半身像','立華 奏的半身像','冷凍光束槍'),'result' => array('佐佑理學姐的塑料水槍','WG',333,10,'ikr'),),
	array('class' => 'wg', 'stuff' => array('『高性能環形激光』','增幅設備','巨大透鏡'),'result' => array('【質子撞擊炮】','WG',450,200,'udo'),),
	array('class' => 'wg', 'stuff' => array('『高性能黑洞激光』','增幅設備','巨大透鏡'),'result' => array('【重力衝擊炮】','WG',450,200,'Ndo'),),
	array('class' => 'wg', 'stuff' => array('『高性能雙重激光』','增幅設備','巨大透鏡'),'result' => array('【最終鬼畜兵器】','WG',640,200,'uNdo'),),
	array('class' => 'wg', 'stuff' => array('【最終鬼畜兵器】','『奧丁巨核裝備』','非法槍械部件'),'result' => array('【霜火協奏曲】','WG',1024,256,'uNwdr'),),
	
	array('class' => 'wd', 'stuff' => array('輕油','肥料'),'result' => array('火藥','X',1,1,),),
	array('class' => 'wd', 'stuff' => array('信管','火藥'),'result' => array('★炸藥★','WD',160,60,'d'),),
	array('class' => 'wd', 'stuff' => array('導火線','火藥'),'result' => array('★炸藥★','WD',160,60,'d'),),
	array('class' => 'wd', 'stuff' => array('水','地雷'),'result' => array('水鴛鴦','WD',50,36,'d'),),
	array('class' => 'wd', 'stuff' => array('★炸藥★','水鴛鴦'),'result' => array('★C4★','WD',250,20,'d'),),
	array('class' => 'wd', 'stuff' => array('探測器電池','打火機'),'result' => array('☆自爆電池☆','WD',140,32,'d'),),
	array('class' => 'wd', 'stuff' => array('☆自爆電池☆','電磁IED','脈衝防線'),'result' => array('脈衝蓄電池','WD',140,60,'ed'),),
	array('class' => 'wd', 'stuff' => array('☆自爆電池☆','輻射IED','『破壞之杖』'),'result' => array('輻射蓄電池','WD',178,100,'pd'),),
	array('class' => 'wd', 'stuff' => array('伏特加','一杯八分滿的啤酒'),'result' => array('深水炸彈『depth charge』','WD',133,45,'d'),),
	array('class' => 'wd', 'stuff' => array('深水炸彈『depth charge』','火藥'),'result' => array('莫洛托夫雞尾酒','WD',150,40,'ud'),),
	array('class' => 'wd', 'stuff' => array('咖啡酒','百利甜','伏特加'),'result' => array('奇怪的三色飲料','HB',133,2),),
	array('class' => 'wd', 'stuff' => array('奇怪的三色飲料','打火機','杯子'),'result' => array('B-52轟炸機','WD',160,35,'ud'),),
	array('class' => 'wd', 'stuff' => array('密封的酒瓶','★闊劍地雷★','莫洛托夫雞尾酒'),'result' => array('烈焰風暴','WD',92,300,'urdZ'),),
	array('class' => 'wd', 'stuff' => array('密封的酒瓶','★闊劍地雷★','B-52轟炸機'),'result' => array('烈焰風暴','WD',92,250,'urdZ'),),
	array('class' => 'wd', 'stuff' => array('伏特加','檸檬汁','紅石榴汁'),'result' => array('【烈焰紅唇】','HB',233,2),),
	array('class' => 'wd', 'stuff' => array('【烈焰紅唇】','密封的酒瓶'),'result' => array('★血腥瑪麗★Bloody Mary','WD',310,150,'dw'),),
	array('class' => 'wd', 'stuff' => array('伏特加','牛肉湯','バカ⑨製冰塊'),'result' => array('【燃燒的雞尾酒】','HB',233,2),),
	array('class' => 'wd', 'stuff' => array('【燃燒的雞尾酒】','密封的酒瓶'),'result' => array('★公牛子彈★Bull Shot','WD',210,300,'dr'),),
	array('class' => 'wd', 'stuff' => array('★血腥瑪麗★Bloody Mary','★公牛子彈★Bull Shot','密封的酒瓶'),'result' => array('★血腥公牛★Bloody Bull','WD',520,450,'dwr'),),
	array('class' => 'wd', 'stuff' => array('☆自爆電池☆','★時停懷錶★'),'result' => array('寒冰炸彈','WD',260,45,'i'),),
	array('class' => 'wd', 'stuff' => array('『祝福寶石』','★瓶裝幽靈★','某種電子零件'),'result' => array('★幽靈衝擊★','WD',320,200,'Nn'),),
	array('class' => 'wd', 'stuff' => array('★幽靈衝擊★','《魔女的魔導書》','筆記本電腦'),'result' => array('奧術飛彈','WD',400,300,'Nnr'),),
	array('class' => 'wd', 'stuff' => array('寒冰炸彈','奧術飛彈','烈焰風暴'),'result' => array('★BIUBIUBIU★','WD',600,400,'ZnNdr'),),

	array('class' => 'w', 'stuff' => array('數據……碎片','電子馬克筆','天然屬性也是很可怕的！'),'result' => array('黑色奪魂曲','DB',57,77,'ZBb'),),
	array('class' => 'w', 'stuff' => array('『午夜鐘聲』','『午夜鐘聲』','『午夜鐘聲』'),'result' => array('電子馬克筆','DA',53,75,'Z'),),
	
	array('class' => 'item', 'stuff' => array('生命探測器','增幅設備'),'result' => array('廣域生命探測器','ER',1,1,2),),
	array('class' => 'item', 'stuff' => array('早苗麪包','仙貝麪包','咖喱麪包','紅豆麪包'),'result' => array('天然呆四面的獎賞','Z',1,1,'z'),),
	array('class' => 'item', 'stuff' => array('安雅人體冰雕','火把'),'result' => array('武器師安雅的獎賞','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('安雅人體冰雕','解凍藥水'),'result' => array('武器師安雅的獎賞','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('手機','筆記本電腦'),'result' => array('移動PC','EE',1,1,),),
	array('class' => 'item', 'stuff' => array('高壓線圈','原型武器G','原型武器C','某種機械設備'),'result' => array('電磁發射裝置','X',1,1,''),),
	//array('class' => 'item', 'stuff' => array('风见 幽香的ID卡','坂持 金发的ID卡','御坂 美琴的ID卡'),'result' => array('游戏解除钥匙','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('社員專用的ID卡','社員專用的ID卡','社員專用的ID卡'),'result' => array('遊戲解除鑰匙','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('★荊棘式電子地雷★','★闊劍地雷★','★全圖不唯一的野生巨大香蕉★'),'result' => array('★一發逆轉神話★','TNc',1,1,'x'),),
	array('class' => 'item', 'stuff' => array('水','黑色雛菊','白色方塊'),'result' => array('風祭河水','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('水','黑色方塊','白色雛菊'),'result' => array('儀水鏡','Y',1,1,),),
	array('class' => 'item', 'stuff' => array('風祭河水','儀水鏡','白色雛菊','黑色雛菊'),'result' => array('八咫鏡','DH',1,'∞','b'),),
	
	array('class' => 'pokemon', 'stuff' => array('《小黃的草帽》','《小黃的釣魚竿》','《小黃的行軍靴》'),'result' => array('《小黃的精靈球》','WC',233,'∞',),),
	array('class' => 'pokemon', 'stuff' => array('《小黃的精靈球》','《小黃的收服特訓》'),'result' => array('《小黃的超級球》','WC',233,'∞','Zir'),),
	array('class' => 'pokemon', 'stuff' => array('白色的羽毛','金色方塊'),'result' => array('鳳凰之羽','WK',20,200,'u'),),
	array('class' => 'pokemon', 'stuff' => array('白色的羽毛','銀色方塊'),'result' => array('露琪亞之羽','WK',50,200,'i'),),
	array('class' => 'pokemon', 'stuff' => array('《小黃的收服特訓》','《小黃的超級球》','《小黃的常磐之力》'),'result' => array('《小黃的大師球》','WC',386,'∞','Zrd'),),
	array('class' => 'pokemon', 'stuff' => array('鳳凰之羽','《小黃的超級球》','《小黃的常磐之力》'),'result' => array('《小黃的大師球》','WC',386,'∞','ucrd'),),
	array('class' => 'pokemon', 'stuff' => array('露琪亞之羽','《小黃的超級球》','《小黃的常磐之力》'),'result' => array('《小黃的大師球》','WC',386,'∞','icrd'),),
	array('class' => 'pokemon', 'stuff' => array('鳳凰之羽','露琪亞之羽','《小黃的超級球》','《小黃的常磐之力》'),'result' => array('《小黃的大師球》','WC',386,'∞','Zcrd'),),
	
	array('class' => 'key', 'stuff' => array('月宮 亞由的半身像','神尾 觀鈴的半身像','古河 渚的半身像'),'result' => array('四季流轉的詠歎調','WP',750,1,'N'),),
	array('class' => 'key', 'stuff' => array('天澤 鬱末的半身像','長森 瑞佳的半身像','棗 鈴的半身像'),'result' => array('旁觀輪迴的覆唱詩','WK',750,1,'n'),),
	array('class' => 'key', 'stuff' => array('神北 小毬的半身像','一之瀨 琴美的半身像','SSS團長的半身像'),'result' => array('天然屬性也是很可怕的！','WD',160,46,'zd'),),
	array('class' => 'key', 'stuff' => array('天然屬性也是很可怕的！','篝醬的奇蹟☆膠帶～刃'),'result' => array('【KEY系巴嘎彈】','WD',1800,5,'Rz'),),
	array('class' => 'key', 'stuff' => array('【KEY系巴嘎彈】','紅色的絲帶'),'result' => array('【KEY系超級巴嘎彈】','WD',1800,5,'zd'),),
	array('class' => 'key', 'stuff' => array('四季流轉的詠歎調','旁觀輪迴的覆唱詩'),'result' => array('【KEY系催淚彈】','WD',3600,5,'zd'),),
	array('class' => 'key', 'stuff' => array('手機','二重戰鬥匕首','《BR大逃殺攻略》','『尋星勇者』'),'result' => array('【KEY系未來彈】','WP',860,5,'zd'),),
	array('class' => 'key', 'stuff' => array('提示紙條K','提示紙條E','提示紙條Y','提示紙條D'),'result' => array('【KEY系生命彈】','WG',860,5,'zdr'),),
	array('class' => 'key', 'stuff' => array('【KEY系未來彈】','【戀歌】','破滅未來的殘光','來自未來的奇蹟'),'result' => array('【春雨夏海，秋葉冬雪】','DB',600,600,'ZBb'),),
	array('class' => 'key', 'stuff' => array('水','黑色雛菊','白色雛菊','樹葉'),'result' => array('生命之源','Z',1200,1,'z'),),
	array('class' => 'key', 'stuff' => array('生命之源','黑色方塊','白色雛菊'),'result' => array('紅色的絲帶','DB',1200,1,'Aa'),),
	array('class' => 'key', 'stuff' => array('生命之源','黑色雛菊','白色方塊'),'result' => array('紅色的絲帶','DA',1200,1,'Aa'),),
	array('class' => 'key', 'stuff' => array('生命之源','黑色方塊','白色方塊'),'result' => array('紅色的絲帶','WP',1200,1,'u'),),
	array('class' => 'key', 'stuff' => array('生命之源','黑色雛菊','白色雛菊'),'result' => array('紅色的絲帶','WK',1200,1,'N'),),
	array('class' => 'key', 'stuff' => array('紅色的絲帶','紅色的絲帶','生命之源'),'result' => array('【KEY系燃燒彈】','WF',4800,2,'Nuz'),),
	array('class' => 'key', 'stuff' => array('生命之源','對魔物用卵石'),'result' => array('捨身成就之羈絆','WCF',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','二重戰鬥匕首'),'result' => array('微小日常之愛戀','WGK',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','巨大路燈柱'),'result' => array('無盡散花之涅磐','WKP',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','黑魔法-權利'),'result' => array('無法推卸的命運','WDG',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','『9mm魯格槍』'),'result' => array('破滅未來的殘光','WFK',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','紅色的絲帶'),'result' => array('來自未來的奇蹟','WCP',233,20,'Z'),),
	array('class' => 'key', 'stuff' => array('生命之源','微小日常之愛戀'),'result' => array('【戀歌】','ss',98,98,'Z'),),
	array('class' => 'key', 'stuff' => array('紅色的絲帶','紅色的絲帶','紅色的絲帶','紅色的絲帶','紅色的絲帶'),'result' => array('篝醬的奇蹟☆絲帶～刃','WK',4200,100,'cjN'),),
	array('class' => 'key', 'stuff' => array('黑色雛菊','白色雛菊'),'result' => array('篝醬的奇蹟☆膠帶～刃','WK',42,100,'cjN'),),
	array('class' => 'hidden', 'stuff' => array('銀色盒子','移動PC'),'result' => array('越獄後的銀色盒子','Z',1,1,'Z'),),
	array('class' => 'hidden', 'stuff' => array('銀色盒子','筆記本電腦'),'result' => array('越獄後的銀色盒子','Z',1,1,'Z'),),
	array('class' => 'key', 'stuff' => array('■秋刀魚罐頭■','■銀白口哨■','越獄後的銀色盒子'),'result' => array('羣青多面體','Z',1,1,'Z'),),
	array('class' => 'key', 'stuff' => array('■彩色玻璃珠■','■奇怪的袋子■','越獄後的銀色盒子'),'result' => array('羣青多面體','Z',1,1,'Z'),),
	array('class' => 'key', 'stuff' => array('■機械花束■','■巨大燈泡■','越獄後的銀色盒子'),'result' => array('羣青多面體','Z',1,1,'Z'),),
	array('class' => 'key', 'stuff' => array('■速溶咖啡■','Untainted Glory','越獄後的銀色盒子'),'result' => array('羣青多面體','Z',1,1,'Z'),),

	
	array('class' => 'cube', 'stuff' => array('綠色方塊','銀色方塊'),'result' => array('炙熱的綬帶','DH',180,80,),),
	array('class' => 'cube', 'stuff' => array('紅色方塊','黃色方塊'),'result' => array('堅強戒指','DA',180,80,),),
	array('class' => 'cube', 'stuff' => array('金色方塊','水晶方塊'),'result' => array('活力之靴','DF',180,80,),),
	array('class' => 'cube', 'stuff' => array('紅色方塊','銀色方塊'),'result' => array('紅寶石方塊','X',1,1,),),
	array('class' => 'cube', 'stuff' => array('金色方塊','綠色方塊'),'result' => array('藍寶石方塊','X',1,1,),),
	array('class' => 'cube', 'stuff' => array('藍色方塊','黃色方塊'),'result' => array('綠寶石方塊','X',1,1,),),
	array('class' => 'cube', 'stuff' => array('紅寶石方塊','藍寶石方塊'),'result' => array('綠寶石方塊','X',1,2,),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','黃色方塊'),'result' => array('黃色的寶石槍','WG',240,180,'e'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','紅色方塊'),'result' => array('紅色的寶石刀','WK',240,180,'u'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','藍色方塊'),'result' => array('藍色的寶石錘','WP',240,180,'i'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','綠色方塊'),'result' => array('綠色的寶石鏢','WC',240,180,'p'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','金色方塊'),'result' => array('金色的寶石炸彈','WD',240,180,'d'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','銀色方塊'),'result' => array('銀色的寶石符卡','WF',240,180,'w'),),
	array('class' => 'cube', 'stuff' => array('紅色的寶石刀','悲嘆之種'),'result' => array('★恐懼的黑色安息日★','WK',240,320,'rud'),),
	array('class' => 'cube', 'stuff' => array('銀色的寶石符卡','悲嘆之種'),'result' => array('★失落的銀色鎮魂歌★','WF',240,320,'rwd'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','水晶方塊'),'result' => array('水晶寶石盾','DA',240,180,'PC'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','紅寶石方塊'),'result' => array('珍珠頭盔','DH',360,180,'KDa'),),
	array('class' => 'cube', 'stuff' => array('綠寶石方塊','藍寶石方塊'),'result' => array('鑽石靴子','DF',360,180,'GFa'),),
	array('class' => 'cube', 'stuff' => array('紅寶石方塊','紅色方塊'),'result' => array('深紅色的項鍊','A',240,180,'aM'),),
	array('class' => 'cube', 'stuff' => array('藍寶石方塊','藍色方塊'),'result' => array('蔚藍色的項鍊','A',240,180,'Hc'),),
	array('class' => 'cube', 'stuff' => array('黃色方塊','黃色方塊','黃色方塊'),'result' => array('★高壓電擊★','WD',122,251,'red'),),
	array('class' => 'cube', 'stuff' => array('紅色方塊','紅色方塊','紅色方塊'),'result' => array('★烈焰衝撞★','WP',122,122,'ru'),),
	array('class' => 'cube', 'stuff' => array('綠色方塊','綠色方塊','綠色方塊'),'result' => array('★飛葉快刀★','WK',122,122,'Zrp'),),
	array('class' => 'cube', 'stuff' => array('藍色方塊','藍色方塊','藍色方塊'),'result' => array('★急凍光線★','WG',122,251,'ric'),),
	array('class' => 'cube', 'stuff' => array('金色方塊','金色方塊','金色方塊'),'result' => array('★齒輪飛碟★','WC',122,386,'rd'),),
	array('class' => 'cube', 'stuff' => array('銀色方塊','銀色方塊','銀色方塊'),'result' => array('★精神破壞★','WF',122,122,'rw'),),
	array('class' => 'cube', 'stuff' => array('水晶方塊','水晶方塊','水晶方塊'),'result' => array('★滅亡之歌★','TN',960,2,),),
	
	
	array('class' => 'wf', 'stuff' => array('空白符卡','☆博麗護符☆'),'result' => array('夢符『夢想妙珠』','WF',40,'∞','r'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','☆山蘑菇粉☆'),'result' => array('星符『星塵狂歡』','WF',60,'∞','u'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','☆守矢神籤☆'),'result' => array('秘術『一子單傳的彈幕』','WF',70,'∞','d'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','★時停懷錶★'),'result' => array('時符『Private Square』','WF',150,'∞','i'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','★瓶裝幽靈★'),'result' => array('幽鬼劍『妖童餓鬼之斷食』','WF',150,'∞','c'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','《文文。新聞》'),'result' => array('風符『風神一扇』','WF',200,'∞','d'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','★制御棒★','向日葵'),'result' => array('『地獄的人造太陽』','WF',522,'∞',),),
	array('class' => 'wf', 'stuff' => array('空白符卡','冰凍青蛙','バカ⑨製冰塊'),'result' => array('冰符『Icicle Fall』','WF',9,'∞','ir'),),
	array('class' => 'wf', 'stuff' => array('西瓜','水果刀','磨刀石'),'result' => array('西瓜刀','WK',99,'∞','c'),),
	array('class' => 'wf', 'stuff' => array('冰沙','小棍棒','御神籤'),'result' => array('冰棍棒','WP',19,29,'r'),),
	array('class' => 'wf', 'stuff' => array('冰符『Icicle Fall』','西瓜刀','冰棍棒'),'result' => array('曾經的榮光-深藍','WF',99,'∞','cri'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','【觸手的萃取液】','《東方永夜抄》'),'result' => array('紫奧義『彈幕結界』','WF',320,'∞','rd'),),
	array('class' => 'wf', 'stuff' => array('時符『Private Square』','幻之刃','永恆飛刃','銀色方塊'),'result' => array('『咲夜的世界』','WF',150,'∞','irc'),),
	array('class' => 'wf', 'stuff' => array('『咲夜的世界』','鮮紅的生血','靈魂的結晶'),'result' => array('『收縮的世界』','WF',450,'∞','irc'),),
	array('class' => 'wf', 'stuff' => array('幽鬼劍『妖童餓鬼之斷食』','☆樓觀劍☆','☆白樓劍☆'),'result' => array('空觀劍『六根清淨斬』','WF',360,'∞','rc'),),
	array('class' => 'wf', 'stuff' => array('藍色方塊','水','空白符卡'),'result' => array('水符「Princess Undine」','WF',30,'∞','iI'),),
	array('class' => 'wf', 'stuff' => array('紅寶石方塊','打火機','空白符卡'),'result' => array('火符「Agni Shine」','WF',40,'∞','uU'),),
	array('class' => 'wf', 'stuff' => array('綠寶石方塊','空白符卡','樹葉'),'result' => array('木符『Sylphy Horn』','WF',50,'∞','wWc'),),
	array('class' => 'wf', 'stuff' => array('藍寶石方塊','天然水','水符「Princess Undine」'),'result' => array('水符『Jerry Fish Princess』','WF',70,'∞','riI'),),
	array('class' => 'wf', 'stuff' => array('土符「Lazy Trilithon」','水符「Princess Undine」','空白符卡'),'result' => array('土&水符『Noachian Deluge』','WF',220,'50','ic'),),
	array('class' => 'wf', 'stuff' => array('黃色方塊','岩石','空白符卡'),'result' => array('土符「Lazy Trilithon」','WF',100,'∞','c'),),
	array('class' => 'wf', 'stuff' => array('土符「Lazy Trilithon」','火符「Agni Shine」','岩石'),'result' => array('火&土符『Lava Cromlech』','WF',240,180,'d'),),
	array('class' => 'wf', 'stuff' => array('金色方塊','電池','空白符卡'),'result' => array('金符「Metal Fatigue」','WF',130,'∞','eE'),),
	array('class' => 'wf', 'stuff' => array('水符「Princess Undine」','金符「Metal Fatigue」'),'result' => array('金&水符『Mercury Poison』','WF',94,'∞','paZ'),),
	array('class' => 'wf', 'stuff' => array('鮮紅的生血','長矛','造霧設備'),'result' => array('神槍『Spear The Gungnir』 ','WF',5500,'1','c'),),
	array('class' => 'wf', 'stuff' => array('《東方幻想鄉》','觸手的力量','【觸手的萃取液】'),'result' => array('夢幻『幻月』 ','WF',900,'∞','rdcm'),),
	array('class' => 'wf', 'stuff' => array('空白符卡','《魔女的魔導書》'),'result' => array('《魔導師速成攻略》','VF',233,'1',''),),
	array('class' => 'wf', 'stuff' => array('向日葵','☆殘頁的魔導書☆','空白符卡'),'result' => array('日符「Royal Flare」-劣','WF',80,'∞','dc'),),
	array('class' => 'wf', 'stuff' => array('月光碎片','☆殘頁的魔導書☆','空白符卡'),'result' => array('月符「Silent Serena」-劣','WF',40,'∞','rc'),),
	array('class' => 'wf', 'stuff' => array('日符「Royal Flare」-劣','《魔女的魔導書》'),'result' => array('日符「Royal Flare」','WF',260,'∞','udc'),),
	array('class' => 'wf', 'stuff' => array('月符「Silent Serena」-劣','《魔女的魔導書》'),'result' => array('月符「Silent Serena」','WF',120,'∞','irc'),),
	array('class' => 'wf', 'stuff' => array('月符「Silent Serena」','日符「Royal Flare」'),'result' => array('日&月符『Royal Diamond Ring』','WF',432,'∞','riud'),),
	array('class' => 'wf', 'stuff' => array('金符「Metal Fatigue」','火符「Agni Shine」','《魔女的魔導書》'),'result' => array('火&金符『St. Elmo Pillar』','WF',330,'∞','ndfc'),),
	array('class' => 'wf', 'stuff' => array('水符『Jerry Fish Princess』','月符「Silent Serena」','消音器','天然水'),'result' => array('水&月符『Silent Deluge』','WF',233,'∞','kZz'),),
	array('class' => 'wf', 'stuff' => array('火符「Agni Shine」','水符「Princess Undine」','木符『Sylphy Horn』','金符「Metal Fatigue」','土符「Lazy Trilithon」'),'result' => array('火水木金土符『賢者之石』','WF',5000,'∞','uipwe'),),
	array('class' => 'wf', 'stuff' => array('月符「Silent Serena」','月符「Silent Serena」','火水木金土符『賢者之石』','金符「Metal Fatigue」'),'result' => array('月月火水木金金符『年中無休』（笑）','WF',65500,'∞','rd'),),
	array('class' => 'wf', 'stuff' => array('日&月符『Royal Diamond Ring』','夢幻『幻月』','神槍『Spear The Gungnir』','紫奧義『彈幕結界』'),'result' => array('模式『EX』','WF',72000,'∞','crdZ'),),
	
	array('class' => 'ocg', 'stuff' => array('「被封印的艾克佐迪亞」','「被封印者的左腕」','「被封印者的右腕」','「被封印者的左足」','「被封印者的右足」'),'result' => array('「被封印的黑暗大法師」','WC',8192,1,),),
	array('class' => 'ocg', 'stuff' => array('「被封印的黑暗大法師」','★神卡認證★'),'result' => array('『黑暗大法師』','WC12',8192,'∞','AaZ'),),
  array('class' => 'ocg', 'stuff' => array('「隼騎士」-仮','☆四星認證☆'),'result' => array('「隼騎士」','WC03',100,'∞','rj'),),
	array('class' => 'ocg', 'stuff' => array('「V-噴氣虎」-仮','☆四星認證☆'),'result' => array('「V-噴氣虎」','WC04',160,'180','p'),),
	array('class' => 'ocg', 'stuff' => array('「W-彈射飛翼」-仮','☆四星認證☆'),'result' => array('「W-彈射飛翼」','WC04',130,'150','u'),),
	array('class' => 'ocg', 'stuff' => array('「X-首領加農」-仮','☆四星認證☆'),'result' => array('「X-首領加農」','WC04',180,'150','i'),),
	array('class' => 'ocg', 'stuff' => array('「Y-龍頭」-仮','☆四星認證☆'),'result' => array('「Y-龍頭」','WC04',150,'160','e'),),
	array('class' => 'ocg', 'stuff' => array('「Z-金屬履帶」-仮','☆四星認證☆'),'result' => array('「Z-金屬履帶」','WC04',150,'130','w'),),
	array('class' => 'ocg', 'stuff' => array('「V-噴氣虎」','「W-彈射飛翼」'),'result' => array('「VW-強擊虎」','WC06',200,'∞','pu'),),
	array('class' => 'ocg', 'stuff' => array('「X-首領加農」','「Y-龍頭」','「Z-金屬履帶」'),'result' => array('「XYZ-神龍炮」','WC08',280,'∞','iew'),),
	array('class' => 'ocg', 'stuff' => array('「VW-強擊虎」','「XYZ-神龍炮」'),'result' => array('「VWXYZ-神龍強擊炮」','WC08',320,'∞','puiew'),),
	array('class' => 'ocg', 'stuff' => array('「V-噴氣虎」','「W-彈射飛翼」','「X-首領加農」','「Y-龍頭」','「Z-金屬履帶」'),'result' => array('「VWXYZ-神龍強擊炮」','WC08',450,'∞','puiew'),),
	array('class' => 'ocg', 'stuff' => array('「絕對防禦將軍」-仮','☆六星認證☆'),'result' => array('「絕對防禦將軍」','WC06',250,'∞','A'),),
	array('class' => 'ocg', 'stuff' => array('「人造人-念力震懾者」-仮','☆六星認證☆'),'result' => array('「人造人-念力震懾者」','WC06',240,'∞','NM'),),
	array('class' => 'ocg', 'stuff' => array('「惡魔召喚」-仮','☆六星認證☆'),'result' => array('「惡魔召喚」','WC06',250,'∞','c'),),
	array('class' => 'ocg', 'stuff' => array('「真紅眼黑龍」-仮','☆八星認證☆'),'result' => array('「真紅眼黑龍」','WC07',240,'∞','u'),),
	array('class' => 'ocg', 'stuff' => array('「真紅眼黑龍」','★神卡認證★'),'result' => array('「真紅眼闇龍」','WC09',2400,'∞','cruZ'),),
	array('class' => 'ocg', 'stuff' => array('「真紅眼黑龍」','「金屬化·魔法反射裝甲」'),'result' => array('「真紅眼黑龍鐵龍」','WC08',280,'∞','uA'),),
	array('class' => 'ocg', 'stuff' => array('「惡魔召喚」','「真紅眼黑龍」'),'result' => array('「暗黑魔龍」','WC09',320,'∞','cru'),),
	array('class' => 'ocg', 'stuff' => array('「左輪手槍龍」-仮','☆八星認證☆'),'result' => array('「左輪手槍龍」','WC07',260,'∞','r'),),
	array('class' => 'ocg', 'stuff' => array('「破龍劍士」-仮','☆八星認證☆'),'result' => array('「破龍劍士」','WC07',260,'∞','cC'),),
	array('class' => 'ocg', 'stuff' => array('「黑魔術師」-仮','☆八星認證☆'),'result' => array('「黑魔術師」','WC07',250,'∞','cC'),),
	array('class' => 'ocg', 'stuff' => array('「黑魔術師」','「破龍劍士」'),'result' => array('「超魔導劍士-黑暗帕拉丁」','WC08',300,'∞','crdZ'),),
	array('class' => 'ocg', 'stuff' => array('「青眼白龍」-仮','☆八星認證☆'),'result' => array('「青眼白龍」','WC08',300,'∞','d'),),
	array('class' => 'ocg', 'stuff' => array('「青眼白龍」','「青眼白龍」','【逆轉的女神】'),'result' => array('「青眼究極龍」','WC10',450,'∞','crud'),),
	array('class' => 'ocg', 'stuff' => array('「奧西里斯之天空龍」-仮','★神卡認證★'),'result' => array('『奧西里斯之天空龍』','WC10',4000,'∞','AcreZ'),),
	array('class' => 'ocg', 'stuff' => array('「歐貝利斯克之巨神兵」-仮','★神卡認證★'),'result' => array('『歐貝利斯克之巨神兵』','WC10',4000,'∞','AcriZ'),),
	array('class' => 'ocg', 'stuff' => array('「太陽神之翼神龍」-仮','★神卡認證★'),'result' => array('『太陽神之翼神龍』','WC10',4000,'∞','AcruZ'),),
	array('class' => 'ocg', 'stuff' => array('『奧西里斯之天空龍』','『歐貝利斯克之巨神兵』','『太陽神之翼神龍』'),'result' => array('◎光之創造神◎','WC12',65535,'∞','AcrdZ'),),
  array('class' => 'ocg', 'stuff' => array('「電子龍」-仮','☆五星認證☆'),'result' => array('「電子龍」 ★5','WC05',200,'∞','ej'),),
  array('class' => 'ocg', 'stuff' => array('「電子龍」 ★5','「電子龍」 ★5','「電子龍」 ★5'),'result' => array('「電子終結龍」','WC10',256,'∞','Nnrc'),),
	array('class' => 'ocg', 'stuff' => array('「骷髏指揮」-仮','☆四星認證☆'),'result' => array('「骷髏指揮」 ★4','WC04',100,'∞','rj'),),
	array('class' => 'ocg', 'stuff' => array('「殭屍之主」-仮','☆四星認證☆'),'result' => array('「殭屍之主」 ★4','WC04',170,'90','pj'),),
	array('class' => 'ocg', 'stuff' => array('「死靈之顏」-仮','☆四星認證☆'),'result' => array('「死靈之顏」 ★4','WC04',170,'∞','ej'),),
	array('class' => 'ocg', 'stuff' => array('「吸血鬼領主」-仮','☆五星認證☆'),'result' => array('「吸血鬼領主」 ★5','WC05',200,'∞','Aaj'),),
	array('class' => 'ocg', 'stuff' => array('水靈使-艾莉婭 ★3','☆四星認證☆'),'result' => array('憑依裝着-艾莉婭 ★4','WC04',160,'60','ij'),),
	array('class' => 'ocg', 'stuff' => array('火靈使-希塔 ★3','☆四星認證☆'),'result' => array('憑依裝着-希塔 ★4','WC04',160,'80','uj'),),
	array('class' => 'ocg', 'stuff' => array('風靈使-薇茵 ★3','☆四星認證☆'),'result' => array('憑依裝着-薇茵 ★4','WC04',160,'80','cj'),),
	array('class' => 'ocg', 'stuff' => array('暗靈使-達克 ★3','☆四星認證☆'),'result' => array('憑依裝着-達克 ★4','WC04',160,'80','pj'),),
	array('class' => 'ocg', 'stuff' => array('地靈使-奧絲 ★3','☆四星認證☆'),'result' => array('憑依裝着-奧絲 ★4','WC04',160,'80','wj'),),
	array('class' => 'ocg', 'stuff' => array('光靈使-萊娜 ★3','☆四星認證☆'),'result' => array('憑依裝着-萊娜 ★4','WC04',160,'80','ej'),),
	array('class' => 'ocg', 'stuff' => array('英豪冠軍 草雉劍王','《尋星流奧義書》'),'result' => array('英♂豪冠軍 斷♂肛♂劍♂王','WK',444,'∞','Znd'),),
	array('class' => 'ocg', 'stuff' => array('始祖守護者 提拉斯 ☆5 -仮','☆五星認證☆'),'result' => array('始祖守護者 提拉斯 ☆5','WC',240,'∞','uepwi'),),
	array('class' => 'ocg', 'stuff' => array('流星龍 ★10 -仮','☆十星認證☆'),'result' => array('流星龍 ★10','WC10',700,'∞','crj'),),
	array('class' => 'ocg', 'stuff' => array('紅蓮魔龍 ★8 -仮','☆八星認證☆'),'result' => array('紅蓮魔龍 ★8','WC08',500,'25','cdu'),),
	array('class' => 'ocg', 'stuff' => array('紅蓮魔龍 ★8','☆爆裂模式☆'),'result' => array('真紅魔龍/爆裂體 ★10','WC10',250,'∞','cdZ'),),
	array('class' => 'ocg', 'stuff' => array('星塵龍 ★8','☆爆裂模式☆'),'result' => array('星塵龍/爆裂體 ★10','WC10',627,'∞','mr'),),
	array('class' => 'ocg', 'stuff' => array('正義盟軍 光明守望者 ★8 -仮','☆八星認證☆'),'result' => array('正義盟軍 光明守望者 ★8','WC08',260,'∞','rZ'),),
	array('class' => 'ocg', 'stuff' => array('救世魔龍 -仮','☆十星認證☆'),'result' => array('「救世魔龍」 ★10','WC10',950,'∞','uf'),),
	array('class' => 'ocg', 'stuff' => array('救世星龍 -仮','☆十星認證☆','★神卡認證★'),'result' => array('『流天類星龍』 ★12','WC12',4000,'∞','mcrwZ'),),
	
	
	
	
	array('class' => 'hidden', 'stuff' => array('紅寶石方塊','藍寶石方塊','綠寶石方塊','非法槍械部件'),'result' => array('『寶石光束炮-試作型』','WG',1800,144,'ndo'),),
	

	array('class' => 'hidden', 'stuff' => array('歌詞卡片【海洋】','歌詞卡片【大地】','歌詞卡片【星空】'),'result' => array('破滅之詩','Y',1,1,95),),
	array('class' => 'hidden', 'stuff' => array('礦泉水','麪包','女生校服'),'result' => array('Untainted Glory','A',1,1,'Z'),),
	array('class' => 'hidden', 'stuff' => array('礦泉水','麪包','男生校服'),'result' => array('Untainted Glory','A',1,1,'Z'),),
	array('class' => 'hidden', 'stuff' => array('COCO☆醬','YES♂SIR','鼓舞士氣的頭帶'),'result' => array('FFF團集體出動','WG',233,998,'BbdcN'),),
	array('class' => 'hidden', 'stuff' => array('武神之魂','琉璃血'),'result' => array('『C.H.A.O.S』','Y',1,1,),'karma1'=>'-500','karma2'=>'2000',),
	array('class' => 'hidden', 'stuff' => array('《董子語錄》','琉璃血'),'result' => array('『C.H.A.O.S』','Y',1,1,),'karma1'=>'-500','karma2'=>'2000',),
	array('class' => 'hidden', 'stuff' => array('聖光啊!你有看到那個敵人嗎！','琉璃血'),'result' => array('『C.H.A.O.S』','Y',1,1,),'karma1'=>'-500','karma2'=>'2000',),
	array('class' => 'hidden', 'stuff' => array('黑色碎片','十字髮卡'),'result' => array('黑色髮卡','X',1,1,),),
	array('class' => 'hidden', 'stuff' => array('『T.E.R.R.A』','『A.Q.U.A』','『V.E.N.T.U.S』'),'result' => array('『G.A.M.E.O.V.E.R』','Y',1,1,),),
	array('class' => 'hidden', 'stuff' => array('提示紙條K','提示紙條E'),'result' => array('提示紙條Y','WC',1,1,'zd'),),

	);
?>
