<?php

$language = array
	(
	'title' => 'BR大逃殺',
	
	'index' => '首頁',
	'fullwin' => '全屏模式',
	'backindex' => '返回首頁',
	'messages' => '站內郵件',
	'register' => '賬號註冊',
	
	'user' => '帳號資料',
	'game' => '進入遊戲',
	'map' => '戰場地圖',
	'news' => '進行狀況',
	'alive' => '當前倖存',
	'winner' => '歷史優勝',
	'rank' => '玩家排行',
	'help' => '遊戲幫助',
	'homepage' => '官方網站',
	'admin' => '遊戲管理',
	'report' => '官方討論區',
	'vnworld' => '幻想世界',
	'donate' =>'鳴謝名單',
	
	'now' => '當前時刻',
	'gameversion' => '遊戲版本',
	'gameinfo' => '遊戲情報',
	'adminmsg' => '站長留言',
	'systemmsg' => '系統狀況',
	'username' => '賬號',
	'password' => '密碼',
	'welcome' => '歡迎你，{$cuser}！',
	'login' => '登錄',
	'numinfo' => '第 $gamenum 迴游戲 ',
	'gamedate' => '{$month}月{$day}日 星期{$week["$wday"]} {$hour}:{$min}',
	'back' => '返回',
	'submit' => '提交',
	'reset' => '重設',
	
	'basicdata' => '賬户密碼',
	'advanceddata' => '個性化資料',
	'creditsdata' => '積分操作',
	'opass' => '原密碼',
	'npass' => '新密碼',
	'rnpass' => '重複新密碼',
	'editpass' => '修改密碼點此（未完成）',
	'username_comment' => '最長15個英文字符或者漢字，不能出現半角符號',
	'password_comment' => '最長24個字符',
	'motto' => '口頭禪',
	'killmsg' => '殺人宣言',
	'lastword' => '遺言',
	'usertitle' => '頭銜',
	'bgmvolume' => '背景音量',
	'username_comment' => '最長15個英文字符或者漢字，不能出現半角符號',
	'password_comment' => '最長24個字符，留空為不修改',
	'motto_comment' => '寫下彰顯個性的台詞，30個字以內。',
	'killmsg_comment' => '寫下你殺死對手的留言，30個字以內',
	'lastword_comment' => '寫下你不幸被害時的台詞，30個字以內',
	'bgmvolume_comment' => '設置遊戲內背景音樂的默認音量',
	'credits' => '戰鬥力',
	'credits2' => '切糕',
	'lastgame' => '最後遊戲',
	'validgames' => '參加遊戲場數',
	'wingames' => '獲勝場數',
	'winrate' => '勝率',
	'end_achievement' => '結局成就',
	'mixitem_achievement' => '合成成就',
	'battle_achievement' => '戰鬥成就',
	'trap_achievement' => '陷阱成就',
	'other_achievement' => '挑戰成就',
	'lifetime_achievement' => '生涯成就',
	
	
	'valid' => '入場手續',
	'validover' => '入場表格填寫完成',
	'enternotice' => '進入會場',
	'enterbattlefield' => '進入大逃殺戰場',
	'gamestart' => '遊戲開始',
	'enter' => '進入遊戲',
	'quit' => '賬號退出',
	'errormsg' => '出現錯誤',
	
	'tutorial' => '遊戲教程',
	'enterturorial' => '觀看遊戲教程',
	'nexttutorial' => '下一篇教程',

	# vnworld
	'vcreator' => '作者',
	'vstatus' => '提交狀態',
	'viclass' => '道具分組',
	'stf0' => '合成材料一',
	'stf1' => '合成材料二',
	'stf2' => '合成材料三',
	'stf3' => '合成材料四',
	'stf4' => '合成材料五',
	'stf5' => '合成材料六',
	'vitm' => '合成結果',
	'vitmk' => '道具用途',
	'vitme' => '道具效果',
	'vitms' => '道具耐久',
	'vitmsk' => '物品屬性',
	'veitmsk' => '編輯物品屬性',
	'vedit' => '編輯',
	'veback' => '回退',
	
	# in-game
	'name' => '姓名',
	'gender' => '性別',
	'icon' => '頭像',
	'sNo' => '學號',
	'nick' => '頭銜',
	'level' => '等級',
	'club' => '內定稱號',
	'hp' => '生命',
	'sp' => '體力',
	'att' => '攻擊力',
	'def' => '防禦力',
	'combo' => '連鬥',
	'duel' => '死鬥',
	'exp' => '經驗值',
	'weather' => '天氣',
	'status' => '狀態',
	'team' => '隊伍',
	'inf' => '受傷部位',
	'pose' => '基礎姿態',
	'tactic' => '應戰策略',
	'kind1' => '種類',
	'rage' => '怒氣',
	'killnum' => '擊殺數',
	'money' => '金錢',
	'equip' => '裝備',
	'pack' => '包裹',
	'startpack' => '隨機道具',
	'skill' => '熟',
	'command' => '指令',
	'wep' => '武器',
	'arb' => '防具',
	'effect' => '攻擊',
	'cmd_choice' => '你想要做什麼？',
	'chat' => '聊天訊息',
	'moneyunit' => '元',
	'wp' => '毆',
	'wk' => '斬',
	'wg' => '射',
	'wc' => '投',
	'wd' => '爆',
	'wf' => '靈',
	'ss' => '歌魂',
	'karma' => '罪業',
	'skillpoint' => '技能點',
	'newsnotice' => '<span class="evergreen">“各位仍在努力奮戰，真不錯啊。<br />就繼續為了「我們」和「你們自己」戰鬥吧！<br />以下是到現在為止的遊戲狀況。<br />請各位再接再厲。”</span>',
	'useitem' => '>>使用',
	'end' => '遊戲結束！',
	'send' => '發送',
	'refresh' => '刷新',
	'emoji' => '表情',
	'chatswitch' => '切換',
	'maptitle' => '虛擬世界地圖',

	'skillpage_no_skill' => '目前沒有任何技能，去選擇一個內定稱號、或在遊戲中尋找更多技能吧！',

	);


?>
