<?php


$lang = array
(
	'gamename' => '生存遊戲 BRA',
	'succeed' => '成功',
	'fail' => '失敗',
	'exit' => '退出安裝嚮導',
	'enabled' => '允許',
	'writeable' => '可寫',
	'unwriteable' => '不可寫',
	'yes' => '可',
	'no' => '不可',
	'unlimited' => '不限',

	'env_os' => '操作系統',
	'env_php' => 'PHP 版本',
	'env_mysql' => 'MySQL 版本',
	'env_attach' => '附件上傳',
	'env_diskspace' => '磁盤空間',
	'env_dir_writeable' => '目錄寫入',

	'init_log' => '初始化記錄',
	'clear_dir' => '清空目錄',
	'select_db' => '選擇數據庫',
	'create_table' => '建立數據表',
	'init_game' => '初始化遊戲系統',
	'new_game' => '新遊戲準備',

	'install_wizard' => '生存遊戲 - BRA Installation Wizard',
	'welcome' => '歡迎來到 生存遊戲 - BRA 安裝嚮導，安裝前請仔細閲讀 license 檔的每個細節，在您確定可以完全滿足 生存遊戲BRA 的授權協議之後才能開始安裝。readme 檔提供了有關軟件安裝的説明，請您同樣仔細閲讀，以保證安裝進程的順利進行。',
	'current_process' => '當前狀態:',
	'show_license' => '生存遊戲BRA 用户許可協議',
	'agreement' => '請您務必仔細閲讀下面的許可協議',
	'agreement_yes' => '我完全同意',
	'agreement_no' => '我不能同意',
	'configure' => '配置 config.inc.php',
	'check_config' => '檢查配置文件狀態',
	'check_existence' => '存在檢查',
	'check_writeable' => '可寫檢查',
	'edit_config' => '瀏覽/編輯當前配置',
	'variable' => '設置選項',
	'value' => '當前值',
	'comment' => '註釋',
	'dbhost' => '數據庫服務器',
	'dbhost_comment' => '數據庫服務器地址, 一般為 localhost',
	'dbuser' => '數據庫用户名',
	'dbuser_comment' => '數據庫賬號用户名',
	'dbpw' => '數據庫密碼',
	'dbpw_comment' => '數據庫賬號密碼',
	'dbname' => '數據庫名',
	'dbname_comment' => '數據庫名稱',
	'authkey' => '遊戲加密密鑰',
	'authkey_comment' => '必須與插件密鑰相同',
	'tplrefresh' => '模板自動刷新',
	'tplrefresh_comment' => '在長期不修改頁面文件的情況下可以關閉',
	'errorinfo' => '顯示錯誤信息',
	'errorinfo_comment' => '開啓後會泄漏遊戲安裝路徑並可能影響頁面完整性',
	'tablepre' => '表名前綴',
	'tablepre_comment' => '同一數據庫安裝多個遊戲時可改變默認',
	'tablepre_prompt' => '除非您需要在同一數據庫安裝多個 生存遊戲\n 否則,強烈建議您不要修改表名前綴.',
	'moveut' => '服務器時差',
	'moveut_comment' => '在此處設置服務器跟你採用時間的差值，一般用於國外服務器。當前服務器時間:',
	'moveutmin' => '服務器時差（分鐘）',
	'orin_time' => '當前服務器時間：',
	'set_time' => '修正服務器時間：',
	'bbsurl' => '論壇地址',
	'bbsurl_comment' => '安裝遊戲插件的論壇地址',
	'gameurl' => '遊戲程序地址',
	'gameurl_comment' => '用於全屏模式，一般情況下替換為遊戲域名即可',
	'homepage' => '官方網站地址',
	'homepage_comment' => '站長個人主頁或遊戲官方網站的地址',
	'save_config' => '保存配置信息',

	'db_set' => '請設置安裝遊戲的數據庫',
	'db_use_existence' => '使用已存在的數據庫',
	'db_create_new' => '創建新的數據庫',

	'confirm_config' => '上述配置正確',
	'refresh_config' => '刷新修改結果',
	'recheck_config' => '重新檢查設置',
	'check_env' => '檢查當前服務器環境',
	'compare_env' => '生存遊戲BRA 所需環境和當前服務器配置對比',
	'env_required' => '生存遊戲BRA 所需配置',
	'env_best' => '生存遊戲BRA 最佳配置',
	'env_current' => '當前服務器',
	'confirm_preparation' => '請確認已完成如下步驟',
	'install_note' => '安裝嚮導提示',
	'add_admin' => '設置管理員賬號',
	'start_install' => '開始安裝 生存遊戲',
	'installing' => '檢查管理員賬號信息並開始安裝 生存遊戲。',
	'check_admin' => '檢查管理員賬號',
	'check_admin_validity' => '檢查信息合法性',
	'admin_username_invalid' => '用户名空, 長度超過限制或包含非法字符.',
	'admin_invalid' => '您的信息沒有填寫完整.',
	'fail_reason' => '失敗. 原因:',
	'go_back' => '返回上一頁修改',
	'init_file' => '初始化運行目錄與文件',
	'lock_exists' => '您已經安裝過遊戲，為了保證遊戲數據安全，請手動刪除 install.php 文件 和 ./install 文件夾下的所有文件，如果您想重新安裝遊戲，請刪除 gamedata/install.lock 文件，在次運行安裝文件。',

	'config_nonexistence' => '您的 config.inc.php 不存在, 無法繼續安裝, 請用 FTP 將該文件上傳後再試.',
	'config_comment' => '請在下面填寫您的數據庫賬號信息, 通常情況下不需要修改紅色選項內容.',
	'config_unwriteable' => '安裝嚮導無法寫入配置文件, 請核對現有信息, 如需修改, 請通過 FTP 將改好的 config.inc.php 上傳.',

	'php_version_430' => '您的 PHP 版本小於 4.3.0, 無法使用 生存遊戲BRA。',
	'attach_enabled' => '允許/最大尺寸 ',
	'attach_enabled_info' => '您可以上傳附件的最大尺寸: ',
	'attach_disabled' => '不允許上傳附件',
	'attach_disabled_info' => '附件上傳或相關操作被服務器禁止。',
	'mysql_version_323' => '您的 MySQL 版本低於 3.23，安裝無法繼續進行。',
	'unwriteable_template' => '模板目錄(./templates)屬性非 777 或無法寫入，在線編輯模板功能將無法使用。',
	'unwriteable_gamedata' => '數據目錄(./gamedata)屬性非 777 或無法寫入，遊戲運行記錄和備份到數據庫功能將無法使用。',
	'tablepre_invalid' => '您指定的數據表前綴包含點字符(".")，請返回修改。',
	'db_invalid' => '指定的數據庫不存在, 系統也無法自動建立, 無法安裝 生存遊戲BRA.',
	'db_auto_created' => '指定的數據庫不存在, 但系統已成功建立, 可以繼續安裝.',
	'db_not_null' => '數據庫中已經安裝過 生存遊戲BRA, 繼續安裝會清空原有數據.',
	'db_drop_table_confirm' => '繼續安裝會清空全部原有數據，您確定要繼續嗎?',

	'install_abort' => '由於您目錄屬性或服務器配置原因, 無法繼續安裝 生存遊戲BRA, 請仔細閲讀安裝説明.',
	'install_process' => '您的服務器可以安裝和使用 生存遊戲BRA, 請進入下一步安裝.',
	'install_succeed' => '恭喜您，生存遊戲BRA 安裝成功！',
	'goto_game' => '點擊這裏進入遊戲',


	'choice_or_new_db' => '請選擇已存在的數據庫或者新建一個數據庫存放遊戲數據',
	'game_db_conf' => '遊戲數據庫設置',
	'show_and_edit_db_conf' => '瀏覽/編輯當前數據庫配置',
	'choice_one_db' => '請指定一個數據庫',
	'db' => '數據庫',
	'check_user_and_pass' => '檢查數據庫賬號權限',
	'permission' => '權限',
	'status' => '狀態',
	
	'username' => '管理員賬號',
	'username_comment' => '必須為論壇已存在賬號',
	'adminmsg' => '站長留言',
	'adminmsg_comment' => '給用户的公告信息',
	'systemmsg' => '系統狀況',
	'systemmsg_comment' => '顯示系統狀況信息，可與站長留言配合使用',
	'startmode' => '遊戲開始模式',
	'startmode_comment' => '與遊戲開始時間配合使用。',
	'starthour' => '遊戲開始時間',
	'starthour_comment' => '模式0在“當前遊戲管理”裏中設置開始時間，<br>模式1為每天開始小時數，<br>模式2為每局結束後的間隔小時數，<br>模式3為每局結束後的間隔分鐘數<br>',
	'startmin' => '遊戲準備時間',
	'startmin_comment' => '模式2決定整點幾分開始，同時也是開始前的準備時間，<br>一般不要在整點時開局，可能出現問題。',
	'iplimit' => 'IP限制',
	'iplimit_comment' => '0為不限制，數字為允許同時存活人數。',
	'newslimit' => '進行狀況顯示',
	'newslimit_comment' => '進行狀況顯示條數。',
	'alivelimit' => '生存者顯示',
	'alivelimit_comment' => '當前生存者顯示條數。',
	'winlimit' => '優勝者顯示',
	'winlimit_comment' => '歷史優勝者顯示條數。',
	'noiselimit' => '槍聲間隔',
	'noiselimit_comment' => '可以聽到槍聲的最大時間，單位 秒。',
	'chatlimit' => '聊天顯示',
	'chatlimit_comment' => '遊戲內聊天信息顯示條數',
	'chatrefresh' => '聊天刷新',
	'chatrefresh_comment' => '聊天信息的刷新速度，單位 毫秒。',
	'chatinnews' => '遊戲外聊天顯示',
	'chatinnews_comment' => '進行狀況中是否顯示聊天。0為不顯示，數字為顯示條數。',
	'antiAFKertime' => '反掛機間隔時間',
	'antiAFKertime_comment' => '手動清除長時間不動的玩家的最小時間間隔，單位分鐘。',
	'corpseprotect' => '屍體保護時間',
	'corpseprotect_comment' => '決定角色死亡後經過多久才能被他人遇到或者被凸眼魚影響，單位秒。',
	'allow_destory_corpse' => '啓用銷燬屍體',
	'allow_destory_corpse_comment' => '決定是否開啓銷燬屍體功能。0為關閉，1為開啓。',
	'rpup_destory_corpse' => '銷燬屍體懲罰',
	'rpup_destory_corpse_comment' => '開啓銷燬屍體功能後，銷燬屍體後會增加多少RP，0為不增加。',
	'coldtimeon' => '冷卻時間啓動',
	'coldtimeon_comment' => '決定是否啓動冷卻時間，防止利用腳本快速提交。0為不啓動，1為啓動。',
	'showcoldtimer' => '冷卻時間倒計時',
	'showcoldtimer_comment' => '決定是否顯示冷卻時間的倒計時。0為不顯示，1為顯示。',

	'credits2_values' => '切糕換金率',
	'credits2_values_comment' => '場外贊助系統中切糕與遊戲幣的兑換比率。默認：1切糕=2塊錢',
	'sponsor_title' => '場外贊助者頭銜',
	'sponsor_title_comment' => '使用場外贊助系統發送快遞時，在進行狀況內顯示的投資者頭銜。',
	'gnpctype' => '快遞NPC類別',
	'gnpctype_comment' => '使用場外贊助系統發送快遞時，快遞員NPC的類別。默認：90',
	'gnpcsub' => '快遞NPC子類別',
	'gnpcsub_comment' => '使用場外贊助系統發送快遞時，快遞員NPC的子類別。默認：0',
	'no_self_sponsored' => '禁止自我贊助',
	'no_self_sponsored_comment' => '是否禁止使用場外贊助系統給自己發快遞。0為禁止，1為允許。',
	
	'areahour' => '禁區間隔時間',
	'areahour_comment' => '單位：分鐘',
	'areaadd' => '禁區增加數',
	'areaadd_comment' => '每次增加的禁區數量，最小為1',
	'arealimit' => '停止激活禁區數',
	'arealimit_comment' => '注意，是增加禁區的回數，而不是禁區的數量',
	'areaesc' => '自動逃避禁區',
	'areaesc_comment' => '0=關閉。1=所有玩家自動躲避，適合新手較多，不瞭解禁區機制',
	'validlimit' => '激活人數上限',
	'validlimit_comment' => '',
	'combolimit' => '連鬥人數',
	'combolimit_comment' => '停止激活後，人數少於此數值則進入連鬥',
	'deathlimit' => '連鬥人數2',
	'deathlimit_comment' => '停止激活後，死亡人數(包括 npc)大於此數值則進入連鬥',
	'splimit' => '體力上限',
	'splimit_comment' => '角色的最大體力，體力最大值不會增長',
	'hplimit' => '生命上限',
	'hplimit_comment' => '角色0級的最大生命，生命最大值會隨等級增長',
	'sleep_time' => '體力恢復時間',
	'sleep_time_comment' => '恢復體力最大值的1%需要的時間，單位：秒。',
	'heal_time' => '生命恢復時間',
	'heal_time_comment' => '恢復生命最大值的1%需要的時間，單位：秒。',
	'teamlimit' => '組隊人數上限',
	'teamlimit_comment' => '',
	'npclimit' => 'npc數量',
	'npclimit_comment' => '士兵的數量，與其他npc無關',
	'rsgame_bots' => '開局bot數量',
	'rsgame_bots_comment' => '遊戲開始時會初始化的bot數量',

	'startmode_0' => '模式0：手動設定:',
	'startmode_1' => '模式1：每日定時:',
	'startmode_2' => '模式2：整點開始:',
	'startmode_3' => '模式3：間隔開始:',
	'starttime_0' => '設定時間:',
	'starttime_1' => '立即開始:',
	'year' => '年',
	'month' => '月',
	'day' => '日',
	'hour' => '時',
	'min' => '分',

	'license' => '<p class="subtitle">生存遊戲 BRA中文版授權協議 適用於中文用户。<br>本遊戲版權屬 龍游網 www.loongyou.com 所有，未經允許不得用於任何商業用途。</p>',

	'preparation' => '<li>將壓縮包中 生存遊戲BRA 目錄下全部文件和目錄上傳到服務器.</li><li>修改服務器上的 config.inc.php 文件以適合您的配置, 有關數據庫賬號信息請諮詢您的空間服務提供商.</li><li>如果您使用非 WINNT 系統請修改以下屬性:<br>&nbsp; &nbsp; <b>./templates</b> 目錄 777;&nbsp; &nbsp; <b>./gamedata</b> 目錄 777;<br><b>&nbsp; &nbsp;<br></li>',
	
	'emenu' => '系統環境',
	'gmenu' => '當前遊戲',
	
	'options' => '選項',
	'comments' => '説明',
	'groups' => '權限',
	'configmng' => '服務參數設置',
	'configmng_comment' => '配置服務器時差等遊戲底層參數<br>對應config.inc.php',
	'systemmng' => '系統環境設置',
	'systemmng_comment' => '配置跟全局環境相關的系統參數<br>對應system.php',
	'gamecfgmng' => '遊戲數據配置',
	'gamecfgmng_comment' => '設置跟單局遊戲相關的遊戲參數<br>對應gamecfg_x.php',
	'gamemng' => '當前遊戲管理',
	'gamemng_comment' => '管理當前局的玩家、NPC、天氣等數據<br>對應數據庫及gameinfo.php',
	'banlistmng' => '屏蔽列表管理',
	'banlistmng_comment' => '管理用户名和IP的屏蔽信息<br>對應banlist.list',
	'gmlist' => 'GM權限管理',
	'gmlist_comment' => '設置各管理員的權限',
	'urlist' => '玩家帳户管理',
	'urlist_comment' => '管理玩家帳户信息',
	'vnmixlist' => '合成列表管理',
	'vnmixlist_comment' => '檢查或退回已被採納的合成',
	'gamecheck' => '當前遊戲自檢',
	'gamecheck_comment' => '修正遊戲人數異常和移動下拉框消失的功能',
	'templates_clean' => '清空模板緩存',
	'templates_clean_comment' => '清空已生成的模板緩存文件',
	'roommng' => '臨時性房間管理',
	'roommng_comment' => '強制關閉指定編號的房間<br>不能關閉0號大房間（臨時功能）',
	'resourcemng' => '遊戲資源管理',
	'resourcemng_comment' => '管理地圖物品/商店/開局物品與NPC配置，支持按RuleSet編輯',
	
	'pcmng' => '玩家數據管理',
	'pcmng_comment' => '修改當前局玩家的各數值，不影響帳號',
	'npcmng' => 'NPC數據管理',
	'npcmng_comment' => '修改當前局NPC的各數值，不影響其他局',
	'wthmng' => '當前天氣管理',
	'wthmng_comment' => '修改當前天氣狀況',
	'gameinfomng' => '遊戲狀況管理',
	'gameinfomng_comment' => '修改當前局遊戲的時間、狀態等基礎信息',
	'antiAFKmng' => '反掛機功能',
	'antiAFKmng_comment' => '手動清除一定時間內未行動的玩家',
	'sttimemng' => '開始時間管理',
	'sttimemng_comment' => '設定下局遊戲的開始時間',
	
	'on' => '開啓',
	'off' => '關閉',
	
	'mygroup' => '您的權限：',
	'command_ok' => '操作成功完成',
	'goto_menu' => '返回管理菜單',
);


?>